"""init db

Revision ID: 988207abe701
Revises:
Create Date: 2026-09-06 14:22:31.258841

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "988207abe701"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # create schema
    op.execute("CREATE SCHEMA IF NOT EXISTS bi")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_source",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "provider", sa.Enum("SUPERSET", "RAW_DB", name="provider"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="bi",
    )
    op.create_table(
        "dataset",
        sa.Column("data_source_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["bi.data_source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="bi",
    )
    op.create_table(
        "analytic",
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["bi.dataset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="bi",
    )
    op.create_table(
        "dataset_column",
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("data_type", sa.String(), nullable=False),
        sa.Column("is_temporal", sa.Boolean(), nullable=False),
        sa.Column("expression", sa.Text(), nullable=True),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["bi.dataset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="bi",
    )
    op.create_table(
        "metric",
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("expression", sa.Text(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["bi.dataset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="bi",
    )
    op.create_table(
        "query",
        sa.Column("analytic_id", sa.Uuid(), nullable=False),
        sa.Column("row_limit", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analytic_id"],
            ["bi.analytic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="bi",
    )
    op.create_table(
        "visualization",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column("analytic_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "LINE",
                "BAR",
                "BOX",
                "TABLE",
                "PIVOT_TABLE",
                "MIXED_CHART",
                "SANKEY_CHART",
                "AREA_CHART",
                "HISTOGRAM",
                name="viz_type",
            ),
            nullable=False,
        ),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analytic_id"],
            ["bi.analytic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="bi",
    )
    op.create_table(
        "query_column",
        sa.Column("query_id", sa.Uuid(), nullable=False),
        sa.Column("column_id", sa.Uuid(), nullable=False),
        sa.Column("time_grain", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["column_id"],
            ["bi.dataset_column.id"],
        ),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["bi.query.id"],
        ),
        sa.PrimaryKeyConstraint("query_id", "column_id"),
        schema="bi",
    )
    op.create_table(
        "query_filter",
        sa.Column(
            "clause", sa.Enum("WHERE", "HAVING", name="filter_clause"), nullable=False
        ),
        sa.Column(
            "type",
            sa.Enum("STRUCTURED", "EXPRESSION", name="filter_type"),
            nullable=True,
        ),
        sa.Column(
            "operator",
            sa.Enum(
                "EQ",
                "NEQ",
                "GT",
                "LT",
                "GTE",
                "LTE",
                "LIKE",
                "NOT_LIKE",
                "ILIKE",
                "NOT_ILIKE",
                "IS_NULL",
                "IS_NOT_NULL",
                "IN",
                "NOT_IN",
                "TEMPORAL_RANGE",
                name="filter_operator",
            ),
            nullable=True,
        ),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expression", sa.Text(), nullable=True),
        sa.Column("query_id", sa.Uuid(), nullable=False),
        sa.Column("column_id", sa.Uuid(), nullable=True),
        sa.Column("metric_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["column_id"],
            ["bi.dataset_column.id"],
        ),
        sa.ForeignKeyConstraint(
            ["metric_id"],
            ["bi.metric.id"],
        ),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["bi.query.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="bi",
    )
    op.create_table(
        "query_metric",
        sa.Column("query_id", sa.Uuid(), nullable=False),
        sa.Column("metric_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["metric_id"],
            ["bi.metric.id"],
        ),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["bi.query.id"],
        ),
        sa.PrimaryKeyConstraint("query_id", "metric_id"),
        schema="bi",
    )
    op.create_table(
        "query_order",
        sa.Column("query_id", sa.Uuid(), nullable=False),
        sa.Column("column_id", sa.Uuid(), nullable=True),
        sa.Column("metric_id", sa.Uuid(), nullable=True),
        sa.Column("asc", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["column_id"],
            ["bi.dataset_column.id"],
        ),
        sa.ForeignKeyConstraint(
            ["metric_id"],
            ["bi.metric.id"],
        ),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["bi.query.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("query_id", "position"),
        schema="bi",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("query_order", schema="bi")
    op.drop_table("query_metric", schema="bi")
    op.drop_table("query_filter", schema="bi")
    op.drop_table("query_column", schema="bi")
    op.drop_table("visualization", schema="bi")
    op.drop_table("query", schema="bi")
    op.drop_table("metric", schema="bi")
    op.drop_table("dataset_column", schema="bi")
    op.drop_table("analytic", schema="bi")
    op.drop_table("dataset", schema="bi")
    op.drop_table("data_source", schema="bi")
    op.execute("DROP SCHEMA IF EXISTS bi CASCADE")
    # ### end Alembic commands ###
